'use strict';

const fs = require('fs');
const path = require('path');
const glob = require('glob');

const ROOT = path.dirname(path.dirname(__dirname));
const LANG_DIR = path.join(ROOT, 'src', 'languages');
const OUT_FILE = path.join(ROOT, 'src', 'lib', 'grammar_aliases.js');

/**
 * Pull aliases: [ ... ] string entries from a grammar source file.
 * @param {string} source
 * @returns {string[]}
 */
function extractAliases(source) {
  const match = source.match(/\baliases\s*:\s*\[([\s\S]*?)\]/);
  if (!match) return [];
  return [...match[1].matchAll(/['"]([^'"]+)['"]/g)].map((m) => m[1]);
}

/**
 * @returns {Record<string, string>} aliasOrId (lowercase) -> canonical id
 */
function buildAliasMap() {
  /** @type {Record<string, string>} */
  const map = Object.create(null);
  const files = glob.sync('*.js', { cwd: LANG_DIR });

  for (const file of files) {
    const id = file.replace(/\.js$/, '');
    const source = fs.readFileSync(path.join(LANG_DIR, file), 'utf8');
    const aliases = extractAliases(source);

    map[id.toLowerCase()] = id;
    for (const alias of aliases) {
      map[alias.toLowerCase()] = id;
    }
  }

  // stable key order for readable diffs
  const ordered = {};
  for (const key of Object.keys(map).sort()) {
    ordered[key] = map[key];
  }
  return ordered;
}

/**
 * Write src/lib/grammar_aliases.js (imported by core).
 * @returns {{ count: number, file: string, map: Record<string, string> }}
 */
function writeAliasMap() {
  const map = buildAliasMap();
  const body =
    `// AUTO-GENERATED by tools/esm/build_alias_map.js — do not edit.\n`
    + `/** @type {Record<string, string>} */\n`
    + `export default ${JSON.stringify(map, null, 2)};\n`;
  fs.writeFileSync(OUT_FILE, body);
  return { count: Object.keys(map).length, file: OUT_FILE, map };
}

module.exports = {
  buildAliasMap,
  extractAliases,
  writeAliasMap,
  OUT_FILE
};

if (require.main === module) {
  const result = writeAliasMap();
  console.log(`grammar_aliases: ${result.count} keys -> ${result.file}`);
}
