name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
#        issue-message: 'Message that will be displayed on users'' first issue'
        pr-message: >
          Thank you so much for your first contribution!  It's appreciated.
          One of our maintainers will review it as soon as they can.
          
          If you didn't modify `CHANGES.md` already, please go and do that now and push a second
          commit.  The `CHANGES.md` file is where we keep a running summary of changes so users 
          know what to expect when we issue periodic releases.
          
          Again, thanks.
          
          ---
          
          If by some chance you're just chomping at the bit to make a second PR we do have a "beginner friendly" tag:
          https://github.com/highlightjs/highlight.js/labels/beginner%20friendly
